name: Release

# Integration workflow automatically integrates the code.

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

jobs:
  convert_and_release:
    name: Convert CSV to files
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: execute py script # run the run.py to get the latest data
        run: |
          python convertors/convertor.py

      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
      # - name: Release
      #   uses: actions/create-release@v1
      #   id: create_release
      #   with:
      #     draft: false
      #     prerelease: false
      #     release_name: ${{ steps.date.outputs.date }}
      #     tag_name: ${{ steps.date.outputs.date }}
      #     body: "Expanded drone manufacturer and drone models database"
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      # - name: Upload manufacturers artifact
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./out/manufacturers.json
      #     asset_name: manufacturers.json
      #     asset_content_type: application/json

      # - name: Upload manufacturers with models artifacts
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./out/manufacturersWithModels.json
      #     asset_name: manufacturersWithModels.json
      #     asset_content_type: application/json

      # - name: Upload models artifacts
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./out/models.json
      #     asset_name: models.json
      #     asset_content_type: application/json

      - name: Upload converted files
        uses: actions/upload-pages-artifact@v0.1.0
        with:
          name: github-pages
          path: ./out
      - name: Deploy Github Pages
        uses: actions/deploy-pages@v1
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
